import { PageHeader } from "../components/PageHeader";
import { LegalContentSection } from "../sections/legal/LegalContent";

const SECTIONS = [
  { title: "1. Acceptance of terms", body: `By creating an account or using CodeAtlas ("Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree, do not use the Service.` },
  { title: "2. Description of service", body: `CodeAtlas is a software-as-a-service platform that uses artificial intelligence to generate and improve GitHub repository documentation ("READMEs") based on your connected repositories and optionally provided resume data.` },
  { title: "3. Account registration", body: `You must connect a valid GitHub account to use the Service. You are responsible for maintaining the confidentiality of your session and for all activities that occur under your account.` },
  { title: "4. Acceptable use", body: `You agree not to use the Service to generate content that is unlawful, harmful, or infringes the rights of others. We reserve the right to suspend accounts that violate these rules.` },
  { title: "5. Intellectual property", body: `You retain all rights to your repositories and any content you upload. Content generated by CodeAtlas using your data is owned by you. We retain rights to the Service itself, our brand, and our proprietary AI pipelines.` },
  { title: "6. Subscriptions and billing", body: `Paid plans are billed monthly in advance via Stripe. Subscription fees are non-refundable except where required by law. We may change pricing with 30 days' notice.` },
  { title: "7. Disclaimer of warranties", body: `The Service is provided "as is" without warranties of any kind. Review all generated content before publishing.` },
  { title: "8. Limitation of liability", body: `Our total liability shall not exceed the amount you paid us in the 12 months preceding the claim.` },
  { title: "9. Termination", body: `Either party may terminate at any time. We will retain your data for 30 days after termination, then delete it.` },
  { title: "10. Changes to these terms", body: `We will notify you of material changes by email at least 14 days before they take effect.` },
  { title: "11. Governing law", body: `These Terms are governed by the laws of the applicable jurisdiction. Disputes shall be resolved through binding arbitration.` },
];

export default function Terms() {
  return (
    <div className="flex flex-col">
      <PageHeader
        eyebrow="Effective 1 July 2026"
        title="Terms of Service"
        description="Please read these terms carefully before using CodeAtlas."
      />
      <LegalContentSection
        sections={SECTIONS}
        contactEmail="legal@codeatlas.com"
        contactLabel="Questions about these terms?"
      />
    </div>
  );
}
